imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, src/Card, src/Controller, src/Dice, src/Entity, src/Game, src/Repository, migrations/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                node:
                    version: 16  # Lägg till Node.js

            dependencies:
                override:
                    - npm install
                    - npm run build

            tests:
                override:
                    - command: "composer phpunit"
                      coverage:
                          file: "docs/coverage.clover"
                          format: "php-clover"

        analysis:
            tests:
                override:
                    - php-scrutinizer-run
