imports:
    - php

filter:
    excluded_paths: [vendor/*, tests/*]

build:
    image: default-bionic

    nodes:
        my-tests:
            environment:
                php:
                    version: 8.3.3
                    # version: 8.1.13
                    # version: 8.1.17
                    # version: 8.2.4
                hosts:
                    'local.dev': '127.0.0.1'
                apache2:
                    modules: ['rewrite']
                    sites:
                        symfony_app:
                            web_root: 'public/'
                            host: 'local.dev'
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    #- phpcs-run # Not used, missing config file
    tests:
        override:
            -   command: "composer phpunit"
                # command: "XDEBUG_MODE=coverage vendor/bin/phpunit"
                coverage:
                    file: "docs/coverage.clover"
                    format: "php-clover"
